In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv('turkiye-student-evaluation_generic.csv')

In [3]:
df

instcode  course code  repeat  attendance  difficulty  Orientation  \
0            1            2       1           0           4            3   
1            1            2       1           1           3            3   
2            1            2       1           2           4            5   
3            1            2       1           1           3            3   
4            1            2       1           0           1            1   
...        ...          ...     ...         ...         ...          ...   
5815         3           13       1           0           1            1   
5816         3           13       1           3           4            4   
5817         3           13       1           0           4            5   
5818         3           13       1           1           2            1   
5819         3           13       1           1           2            1   

      Course Objectives  Valua additon  Syllabus Oriented  Assignments  ...  \
0                     3              3                  3            3  ...   
1                     3              3                  3            3  ...   
2                     5              5                  5            5  ...   
3                     3              3                  3            3  ...   
4                     1              1                  1            1  ...   
...                 ...            ...                ...          ...  ...   
5815                  1              1                  1            1  ...   
5816                  4              4                  4            4  ...   
5817                  5              5                  5            5  ...   
5818                  1              1                  1            1  ...   
5819                  1              1                  1            1  ...   

      instructor effictiveness  instructor helpful  instructor positive  \
0                            3                   3                    3   
1                            3                   3                    3   
2                            5                   5                    5   
3                            3                   3                    3   
4                            1                   1                    1   
...                        ...                 ...                  ...   
5815                         1                   1                    1   
5816                         5                   5                    5   
5817                         5                   5                    5   
5818                         1                   1                    1   
5819                         1                   1                    1   

      instructor respectful  class participation  instructor assignment  \
0                         3                    3                      3   
1                         3                    3                      3   
2                         5                    5                      5   
3                         3                    3                      3   
4                         1                    1                      1   
...                     ...                  ...                    ...   
5815                      1                    1                      1   
5816                      5                    4                      5   
5817                      5                    5                      5   
5818                      1                    1                      1   
5819                      1                    1                      1   

      instructor responsiveness  instructor eval sys  instructor solutions  \
0                             3                    3                     3   
1                             3                    3                     3   
2                             5                    5                     5   
3                             

In [7]:
from sklearn.cluster import KMeans

In [8]:
kmeans=KMeans(n_clusters=2)

In [9]:
kmeans.fit(df)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [11]:
kmeans.cluster_centers_

array([[2.57337992, 7.37420584, 1.2433291 , 1.44663278, 2.73348158,
        2.13182973, 2.21982211, 2.36626429, 2.25730623, 2.24047014,
        2.27668361, 2.22871665, 2.20870394, 2.34879288, 2.21537484,
        2.34847522, 2.2023507 , 2.36213469, 2.42121982, 2.42376112,
        2.25635324, 2.59752224, 2.33354511, 2.37452351, 2.40406607,
        2.43773825, 2.44726811, 2.3001906 , 2.27287166, 2.45457433,
        2.34593393, 2.2884371 , 2.45203304],
       [2.38211078, 7.16092814, 1.17964072, 1.94535928, 2.84244012,
        3.87013473, 4.08008982, 4.13585329, 4.05464072, 4.12537425,
        4.08607784, 4.05314371, 4.02357784, 4.12874251, 4.12200599,
        4.16803892, 4.01721557, 4.28031437, 4.31549401, 4.30464072,
        4.24550898, 4.34206587, 4.26983533, 4.30688623, 4.32372754,
        4.33196108, 4.34281437, 4.26422156, 4.22005988, 4.32335329,
        4.25449102, 4.17552395, 4.31661677]])

In [13]:
labels=kmeans.labels_

In [14]:
print(labels)

[0 0 1 ... 1 0 0]


In [16]:
labels.shape

(5820,)

In [39]:
labels=pd.DataFrame(labels,columns=['cluster'])
labels.columns

Index(['cluster'], dtype='object')

In [31]:
df=pd.concat([df,labels],axis=1)

In [32]:
df

instcode  course code  repeat  attendance  difficulty  Orientation  \
0            1            2       1           0           4            3   
1            1            2       1           1           3            3   
2            1            2       1           2           4            5   
3            1            2       1           1           3            3   
4            1            2       1           0           1            1   
...        ...          ...     ...         ...         ...          ...   
5815         3           13       1           0           1            1   
5816         3           13       1           3           4            4   
5817         3           13       1           0           4            5   
5818         3           13       1           1           2            1   
5819         3           13       1           1           2            1   

      Course Objectives  Valua additon  Syllabus Oriented  Assignments  ...  \
0                     3              3                  3            3  ...   
1                     3              3                  3            3  ...   
2                     5              5                  5            5  ...   
3                     3              3                  3            3  ...   
4                     1              1                  1            1  ...   
...                 ...            ...                ...          ...  ...   
5815                  1              1                  1            1  ...   
5816                  4              4                  4            4  ...   
5817                  5              5                  5            5  ...   
5818                  1              1                  1            1  ...   
5819                  1              1                  1            1  ...   

      instructor positive  instructor respectful  class participation  \
0                       3                      3                    3   
1                       3                      3                    3   
2                       5                      5                    5   
3                       3                      3                    3   
4                       1                      1                    1   
...                   ...                    ...                  ...   
5815                    1                      1                    1   
5816                    5                      5                    4   
5817                    5                      5                    5   
5818                    1                      1                    1   
5819                    1                      1                    1   

      instructor assignment  instructor responsiveness  instructor eval sys  \
0                         3                          3                    3   
1                         3                          3                    3   
2                         5                          5                    5   
3                         3                          3                    3   
4                         1                          1                    1   
...                     ...                        ...                  ...   
5815                      1                          1                    1   
5816                      5                          5                    5   
5817                      5                          5                    5   
5818                      1                          1                    1   
5819                      1                          1                    1   

      instructor solutions  isntructor treatment  0  cluster  
0                        3                     3  0      NaN  
1                        3                     3  0      NaN  
2                        5                     5  1      NaN  
3                        3                     3  0      NaN  
4  

In [34]:
df.drop('cluster',inplace=True,axis=1)

In [35]:
df

instcode  course code  repeat  attendance  difficulty  Orientation  \
0            1            2       1           0           4            3   
1            1            2       1           1           3            3   
2            1            2       1           2           4            5   
3            1            2       1           1           3            3   
4            1            2       1           0           1            1   
...        ...          ...     ...         ...         ...          ...   
5815         3           13       1           0           1            1   
5816         3           13       1           3           4            4   
5817         3           13       1           0           4            5   
5818         3           13       1           1           2            1   
5819         3           13       1           1           2            1   

      Course Objectives  Valua additon  Syllabus Oriented  Assignments  ...  \
0                     3              3                  3            3  ...   
1                     3              3                  3            3  ...   
2                     5              5                  5            5  ...   
3                     3              3                  3            3  ...   
4                     1              1                  1            1  ...   
...                 ...            ...                ...          ...  ...   
5815                  1              1                  1            1  ...   
5816                  4              4                  4            4  ...   
5817                  5              5                  5            5  ...   
5818                  1              1                  1            1  ...   
5819                  1              1                  1            1  ...   

      instructor helpful  instructor positive  instructor respectful  \
0                      3                    3                      3   
1                      3                    3                      3   
2                      5                    5                      5   
3                      3                    3                      3   
4                      1                    1                      1   
...                  ...                  ...                    ...   
5815                   1                    1                      1   
5816                   5                    5                      5   
5817                   5                    5                      5   
5818                   1                    1                      1   
5819                   1                    1                      1   

      class participation  instructor assignment  instructor responsiveness  \
0                       3                      3                          3   
1                       3                      3                          3   
2                       5                      5                          5   
3                       3                      3                          3   
4                       1                      1                          1   
...                   ...                    ...                        ...   
5815                    1                      1                          1   
5816                    4                      5                          5   
5817                    5                      5                          5   
5818                    1                      1                          1   
5819                    1                      1                          1   

      instructor eval sys  instructor solutions  isntructor treatment  0  
0                       3                     3                     3  0  
1                       3                     3                     3  0  
2                       5                     5                     5  1  
3                       3     

In [55]:
df[0].unique()

array([0, 1])

In [56]:
pd.value_counts(df[0])

0    3148
1    2672
Name: 0, dtype: int64

In [73]:
df

instcode  course code  repeat  attendance  difficulty  Orientation  \
0            1            2       1           0           4            3   
1            1            2       1           1           3            3   
2            1            2       1           2           4            5   
3            1            2       1           1           3            3   
4            1            2       1           0           1            1   
...        ...          ...     ...         ...         ...          ...   
5815         3           13       1           0           1            1   
5816         3           13       1           3           4            4   
5817         3           13       1           0           4            5   
5818         3           13       1           1           2            1   
5819         3           13       1           1           2            1   

      Course Objectives  Valua additon  Syllabus Oriented  Assignments  ...  \
0                     3              3                  3            3  ...   
1                     3              3                  3            3  ...   
2                     5              5                  5            5  ...   
3                     3              3                  3            3  ...   
4                     1              1                  1            1  ...   
...                 ...            ...                ...          ...  ...   
5815                  1              1                  1            1  ...   
5816                  4              4                  4            4  ...   
5817                  5              5                  5            5  ...   
5818                  1              1                  1            1  ...   
5819                  1              1                  1            1  ...   

      instructor helpful  instructor positive  instructor respectful  \
0                      3                    3                      3   
1                      3                    3                      3   
2                      5                    5                      5   
3                      3                    3                      3   
4                      1                    1                      1   
...                  ...                  ...                    ...   
5815                   1                    1                      1   
5816                   5                    5                      5   
5817                   5                    5                      5   
5818                   1                    1                      1   
5819                   1                    1                      1   

      class participation  instructor assignment  instructor responsiveness  \
0                       3                      3                          3   
1                       3                      3                          3   
2                       5                      5                          5   
3                       3                      3                          3   
4                       1                      1                          1   
...                   ...                    ...                        ...   
5815                    1                      1                          1   
5816                    4                      5                          5   
5817                    5                      5                          5   
5818                    1                      1                          1   
5819                    1                      1                          1   

      instructor eval sys  instructor solutions  isntructor treatment  0  
0                       3                     3                     3  0  
1                       3                     3                     3  0  
2                       5                     5                     5  1  
3                       3     

In [76]:
k=df.groupby(0,axis=1)

In [80]:
ddf=pd.DataFrame(k)
ddf

0                                                  1
0  0.0        0
0     0
1     0
2     1
3     0
4     ...

In [85]:
kmeans.labels_

array([0, 0, 1, ..., 1, 0, 0])

In [87]:
df.to_csv('Clusterd.xlsx')